name: Bug 反馈
description: 当你在代码中发现了一个 Bug，导致应用崩溃或抛出异常，或者有一个组件存在问题，或者某些地方看起来不对劲。
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        感谢对项目的支持与关注。在提出问题之前，请确保你已查看相关开发或使用文档：
        - https://gitee.com/kyrzy0416/rconsole-plugin
  - type: checkboxes
    attributes:
      label: 这个问题是否已经存在？
      options:
        - label: 我已经搜索过现有的问题 (https://gitee.com/kyrzy0416/rconsole-plugin/issues)
          required: true
  - type: textarea
    attributes:
      label: 如何复现
      description: 请详细告诉我们如何复现你遇到的问题，如涉及代码，可提供一个最小代码示例，并使用反引号```附上它
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: 预期结果
      description: 请告诉我们你预期会发生什么。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 实际结果
      description: 请告诉我们实际发生了什么。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 截图或视频
      description: 如果可以的话，上传任何关于 bug 的截图。
      value: |
        [在这里上传图片]
  - type: dropdown
    id: severity
    attributes:
      label: 问题严重程度
      description: 这个bug对使用的影响程度？
      options:
        - 低 - 轻微影响，有变通方案
        - 中 - 影响正常使用，但不阻塞
        - 高 - 严重影响使用或导致崩溃
        - 紧急 - 完全无法使用，需立即修复
      default: 1
    validations:
      required: true
  - type: dropdown
    id: yunzai
    attributes:
      label: 使用的本体
      description: 你当前正在使用的崽？
      options:
        - Miao
        - Trss
        - 其他
    validations:
      required: true
  - type: dropdown
    id: systemType
    attributes:
      label: 系统类型
      description: 你当前正在使用的系统类型？
      options:
        - Windows
        - Linux
        - Mac
    validations:
      required: true
  - type: dropdown
    id: linuxType
    attributes:
      label: Linux类型（如果是）
      description: 你当前正在使用的Linux是什么系统？
      options:
        - Debian
        - Ubuntu
        - Arch
        - CentOS
        - 其他
    validations:
      required: false
  - type: dropdown
    id: component
    attributes:
      label: 相关功能模块
      description: 此bug涉及哪个功能模块？
      options:
        - Bilibili下载
        - 抖音/TikTok下载
        - YouTube下载
        - 音乐功能
        - 链接总结
        - 其他功能
        - 不确定
    validations:
      required: false